management:
  endpoints:
    web:
      base-path: ${ACTUATOR:/actuator}
      exposure:
        include: ["health", "info", "metrics", "env", "beans", "heapdump", "threaddump", "loggers", "prometheus"]
    access:
      default: read-only
  endpoint:
    info:
      access: read-only
    health:
      show-details: always
