spring:
  profiles:
    active: console, database, actuator, service
  application:
      name: connectionTester

server:
  port: ${SERVER_PORT:8000}
  ssl:
    enabled: ${SSL_CHECK:false}
  servlet:
    context-path: /api