spring:
  profiles:
    active: console, database, actuator, service
  application:
      name: connectionTester

server:
  port: ${SERVER_PORT:8000}
  ssl:
    enabled: ${SSL_ENABLE}
    key-store: classpath:/keystore/keystore.p12
    key-store-password:
    key-store-type:
    key-alias: awstest